/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import beans.Albergue;
import ui.listeners.AddAlbergueListener;

/**
 *
 * @author Alex
 */
public class InsertarAlbergueGUI extends javax.swing.JFrame {

    /**
     * Creates new form formularioInsertar
     */
    public InsertarAlbergueGUI() {
        initComponents();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btAceptar = new javax.swing.JButton();
        //llama a listener add Albergue
        
        btAceptar.addActionListener(new AddAlbergueListener(this));
        btCancelar = new javax.swing.JButton();
        panelFormulario = new javax.swing.JPanel();
        lbTipo = new javax.swing.JLabel();
        tfTipo = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        lbCP = new javax.swing.JLabel();
        tfCP = new javax.swing.JTextField();
        lbProvincia = new javax.swing.JLabel();
        cbProvincia = new javax.swing.JComboBox<>();
        lbMunicipio = new javax.swing.JLabel();
        tfMunicipio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfLocalidad = new javax.swing.JTextField();
        lbNucleo = new javax.swing.JLabel();
        tfNucleo = new javax.swing.JTextField();
        lbTelefono1 = new javax.swing.JLabel();
        tfTelefono1 = new javax.swing.JTextField();
        lbTelefono2 = new javax.swing.JLabel();
        tfTelefono2 = new javax.swing.JTextField();
        lbTelefono3 = new javax.swing.JLabel();
        tfTelefono3 = new javax.swing.JTextField();
        lbFax = new javax.swing.JLabel();
        lbWeb = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbCalidad = new javax.swing.JLabel();
        tfWeb = new javax.swing.JTextField();
        tfFax = new javax.swing.JTextField();
        lbCentralReservas = new javax.swing.JLabel();
        tfReservas = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        cbCalidad = new javax.swing.JComboBox<>();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAceptar.setText("Aceptar");

        btCancelar.setText("Cancelar");

        lbTipo.setText("Tipo:");

        lbNombre.setText("Nombre:");

        lbDireccion.setText("Direccion:");

        tfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionActionPerformed(evt);
            }
        });

        lbCP.setText("C. Postal:");

        lbProvincia.setText("Provincia:");

        cbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avila", "Burgos", "Leon", "Palencia", "Salamanca", "Segovia", "Soria", "Valladolid", "Zamora" }));

        lbMunicipio.setText("Municipio:");

        jLabel1.setText("Localidad:");

        lbNucleo.setText("Nucleo:");

        lbTelefono1.setText("Telefono 1:");

        lbTelefono2.setText("Telefono 2:");

        lbTelefono3.setText("Telefono 3:");

        lbFax.setText("Fax:");

        lbWeb.setText("Web:");

        lbEmail.setText("Email:");

        lbCalidad.setText("QCalidad:");

        lbCentralReservas.setText("Central Reservas:");

        cbCalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excelente", "Superior", "Aceptable", "Mala", "Muy Deficiente", " " }));

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMunicipio)
                            .addComponent(tfLocalidad)))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre)
                            .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tfTipo)))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(lbNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNucleo))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCP)
                            .addComponent(lbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDireccion)
                            .addComponent(tfCP)
                            .addComponent(cbProvincia, javax.swing.GroupLayout.Alignment.TRAILING, 0, 125, Short.MAX_VALUE))))
                .addGap(27, 27, 27)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(lbCentralReservas)
                        .addGap(18, 18, 18)
                        .addComponent(tfReservas))
                    .addComponent(lbTelefono2)
                    .addComponent(lbTelefono3)
                    .addComponent(lbFax, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFormularioLayout.createSequentialGroup()
                            .addComponent(lbTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfTelefono2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(tfTelefono1)))
                        .addComponent(tfTelefono3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfWeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmail)
                            .addComponent(lbCalidad))
                        .addGap(38, 38, 38)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono1)
                    .addComponent(tfTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono2)
                    .addComponent(tfTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono3)
                    .addComponent(tfTelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCP)
                    .addComponent(tfCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFax)
                    .addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProvincia)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWeb)
                    .addComponent(tfWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMunicipio)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCalidad)
                    .addComponent(cbCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNucleo)
                    .addComponent(tfNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCentralReservas)
                    .addComponent(tfReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lbTitulo.setText("FORMULARIO DE REGISTRO DE ALBERGUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar)
                    .addComponent(btCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tfDireccionActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarAlbergueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarAlbergueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarAlbergueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarAlbergueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarAlbergueGUI().setVisible(true);
            }
        });
    }

    
    public javax.swing.JTextField getTfCP() {
		return tfCP;
	}

	public void setTfCP(javax.swing.JTextField tfCP) {
		this.tfCP = tfCP;
	}

	public javax.swing.JTextField getTfDireccion() {
		return tfDireccion;
	}

	public void setTfDireccion(javax.swing.JTextField tfDireccion) {
		this.tfDireccion = tfDireccion;
	}

	public javax.swing.JTextField getTfEmail() {
		return tfEmail;
	}

	public void setTfEmail(javax.swing.JTextField tfEmail) {
		this.tfEmail = tfEmail;
	}

	public javax.swing.JTextField getTfFax() {
		return tfFax;
	}

	public void setTfFax(javax.swing.JTextField tfFax) {
		this.tfFax = tfFax;
	}

	public javax.swing.JTextField getTfLocalidad() {
		return tfLocalidad;
	}

	public void setTfLocalidad(javax.swing.JTextField tfLocalidad) {
		this.tfLocalidad = tfLocalidad;
	}

	public javax.swing.JTextField getTfMunicipio() {
		return tfMunicipio;
	}

	public void setTfMunicipio(javax.swing.JTextField tfMunicipio) {
		this.tfMunicipio = tfMunicipio;
	}

	public javax.swing.JTextField getTfNombre() {
		return tfNombre;
	}

	public void setTfNombre(javax.swing.JTextField tfNombre) {
		this.tfNombre = tfNombre;
	}

	public javax.swing.JTextField getTfNucleo() {
		return tfNucleo;
	}

	public void setTfNucleo(javax.swing.JTextField tfNucleo) {
		this.tfNucleo = tfNucleo;
	}

	public javax.swing.JTextField getTfReservas() {
		return tfReservas;
	}

	public void setTfReservas(javax.swing.JTextField tfReservas) {
		this.tfReservas = tfReservas;
	}

	public javax.swing.JTextField getTfTelefono1() {
		return tfTelefono1;
	}

	public void setTfTelefono1(javax.swing.JTextField tfTelefono1) {
		this.tfTelefono1 = tfTelefono1;
	}

	public javax.swing.JTextField getTfTelefono2() {
		return tfTelefono2;
	}

	public void setTfTelefono2(javax.swing.JTextField tfTelefono2) {
		this.tfTelefono2 = tfTelefono2;
	}

	public javax.swing.JTextField getTfTelefono3() {
		return tfTelefono3;
	}

	public void setTfTelefono3(javax.swing.JTextField tfTelefono3) {
		this.tfTelefono3 = tfTelefono3;
	}

	public javax.swing.JTextField getTfTipo() {
		return tfTipo;
	}

	public void setTfTipo(javax.swing.JTextField tfTipo) {
		this.tfTipo = tfTipo;
	}

	public javax.swing.JTextField getTfWeb() {
		return tfWeb;
	}

	public void setTfWeb(javax.swing.JTextField tfWeb) {
		this.tfWeb = tfWeb;
	}


	// Variables declaration - do not modify                     
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox<String> cbCalidad;
    private javax.swing.JComboBox<String> cbProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCP;
    private javax.swing.JLabel lbCalidad;
    private javax.swing.JLabel lbCentralReservas;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFax;
    private javax.swing.JLabel lbMunicipio;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNucleo;
    private javax.swing.JLabel lbProvincia;
    private javax.swing.JLabel lbTelefono1;
    private javax.swing.JLabel lbTelefono2;
    private javax.swing.JLabel lbTelefono3;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbWeb;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JTextField tfCP;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFax;
    private javax.swing.JTextField tfLocalidad;
    private javax.swing.JTextField tfMunicipio;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNucleo;
    private javax.swing.JTextField tfReservas;
    private javax.swing.JTextField tfTelefono1;
    private javax.swing.JTextField tfTelefono2;
    private javax.swing.JTextField tfTelefono3;
    private javax.swing.JTextField tfTipo;
    private javax.swing.JTextField tfWeb;
    // End of variables declaration                   
}
