package ui;

import ui.listeners.BuscarAlbergueListener;
import ui.listeners.InsertarAlbergueListener;
import ui.listeners.ListarAlberguesListener;
import ui.listeners.ModificarAlbergueListener;
import ui.listeners.PrintAlberguesListener;

public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        btListAlbergue = new javax.swing.JButton();
        btAddAlbergue = new javax.swing.JButton();
        btSearchAlbergue = new javax.swing.JButton();
        btEditAlbergue = new javax.swing.JButton();
        btPrintAlbergues = new javax.swing.JButton();
        btDeleteAlbergue = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        archivoItem = new javax.swing.JMenu();
        editarItem = new javax.swing.JMenu();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btListAlbergue.setText("Listar Albergues");
        btListAlbergue.addActionListener(new ListarAlberguesListener());

        btAddAlbergue.setText("Insertar Albergue");
        btAddAlbergue.addActionListener(new InsertarAlbergueListener());
        btSearchAlbergue.setText("Buscar Albergue");
        btSearchAlbergue.addActionListener(new ListarAlberguesListener());

        btEditAlbergue.setText("Modificar Albergue");
        btEditAlbergue.addActionListener(new ModificarAlbergueListener());

        btPrintAlbergues.setText("Imprimir lista Albergues");
        btPrintAlbergues.addActionListener(new PrintAlberguesListener());

        btDeleteAlbergue.setText("Eliminar Albergue");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btListAlbergue)
                    .addComponent(btSearchAlbergue)
                    .addComponent(btAddAlbergue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPrintAlbergues)
                    .addComponent(btEditAlbergue)
                    .addComponent(btDeleteAlbergue))
                .addGap(33, 33, 33))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListAlbergue)
                    .addComponent(btEditAlbergue))
                .addGap(59, 59, 59)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddAlbergue)
                    .addComponent(btPrintAlbergues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSearchAlbergue)
                    .addComponent(btDeleteAlbergue))
                .addGap(30, 30, 30))
        );

        archivoItem.setText("Archivo");
        barraMenu.add(archivoItem);

        editarItem.setText("Editar");
        barraMenu.add(editarItem);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        
        
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu archivoItem;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btAddAlbergue;
    private javax.swing.JButton btDeleteAlbergue;
    private javax.swing.JButton btEditAlbergue;
    private javax.swing.JButton btListAlbergue;
    private javax.swing.JButton btPrintAlbergues;
    private javax.swing.JButton btSearchAlbergue;
    private javax.swing.JMenu editarItem;
    private javax.swing.JPanel panelBotones;

    // End of variables declaration                   
}

